### ISSUE TITLE
The Chinese information garbled

### ISSUE THREAD

**Issue by CodyGuo** [josephspurrier/goversioninfo#10]
The Chinese information garbled

![image](https://cloud.githubusercontent.com/assets/10672966/22735843/90be090e-ee36-11e6-9616-5163ccac7dfc.png)

**Comment by bestbai** [comment]
I also encountered the same problem when using Chinese. I found out that a function [padString] can't handle multibyte utf-8 to unicode.
FOLLOW ME

`func padString(s string, zeros int) []byte {
	/*	b := make([]byte, 0, len(s)*2)
		for _, x := range s {
			b = append(b, byte(x))
			b = append(b, 0x00)
		}
	*/  //The original code above
	b := make([]byte, 0, len([]rune(s))*2)
	for _, x := range s {
		tt := int32(x)
		b = append(b, byte(tt))
		if tt > 255 {
			tt = tt >> 8
			b = append(b, byte(tt))
		} else {
			b = append(b, byte(0))
		}
	}
	for i := 0; i < zeros; i++ {
		b = append(b, 0x00)
	}
	return b
}`

Good Luck !!

**Comment by kitech** [comment]
+1, the fix works fine.

**Comment by josephspurrier** [comment]
Thanks for the fix, I merged it in.
