### ISSUE TITLE
Possible issue when building with race detector?

### ISSUE THREAD

**Issue by bilo1967** [josephspurrier/goversioninfo#11]
Hi,

I've a small project I'm developing, whose windows version has an icon I was able to add thanks to your great tool.

When I try to build the project with: `go build -race` 
I get the following error:

```
> go build -race
# _/[...]/Subs/ws
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/go/additional/mingw64/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\...\AppData\Local\Temp\go-link-099298167\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status
```
Before installing the Mingw64 (and Mingw32) environment the error was that the gcc compiler was missing.

The build runs just fine if I simply remove `resource.syso` from the project directory.

Thank you very much

G.

P.S.
```
> ver
Microsoft Windows [Versione 6.1.7601]

> go version
go version go1.8 windows/amd64
```

**Comment by josephspurrier** [comment]
If you add this flag ``` -64=true``` to the end of your generate command like this ```//go:generate goversioninfo -icon=icon.ico -manifest=hello.exe.manifest -platform-specific=false -64=true``` it should fix the issue. The resource.syso is creating in the i386 format instead of the amd64 format.
