### ISSUE TITLE
Generated resource.syso file should be platform specific

### ISSUE THREAD

**Issue by virtuald** [josephspurrier/goversioninfo#14]
If I use the same directory on Windows and Linux (or if I try to do a Windows build followed by a Linux build), then I get errors that look like this:

```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: i386 architecture of input file `/tmp/go-link-787743683/000000.o' is incompatible with i386:x86-64 output
collect2: error: ld returned 1 exit status
```

The problem is that golang is trying to link the resource.syso file to the linux executable, which of course doesn't work. The solution is to have the generated file be platform specific -- so instead of resource.syso, the generate step should generate `resource_windows_386.syso` or `resource_windows_amd64.syso` depending on the values of the GOARCH variable.

I can use the -o flag to work around this, but it would be a good default to have too.

**Comment by transifex3** [comment]
+1 for generating each files for i386 and x64

There is a compatible error if using with [Go.Rice](https://github.com/GeertJohan/go.rice)


```
PS C:\Users\User\Desktop\GoProject> go build
# _/C_/Users/User/Desktop/GoProject
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `resource.syso' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status
```

**Comment by josephspurrier** [comment]
Thanks for the info, I added this flag so it will output both of the architecture files.
```-platform-specific=true```

**Comment by phatblinkie** [comment]
Please update the readme with this, tripped me up, but otherwise works great, thanks

**Comment by RuntimeRacer** [comment]
I'm running into this error now. Tried all of the above but still getting weird output:
```C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\sge20\AppData\Local\Temp\go-link-921414442\000001.o' is incompatible with i386:x86-64 output
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: multiple non-default manifests
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: multiple non-default manifests
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 10 (VERSION) name: 1 lang: 409
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: e (GROUP_ICON) name: 2 lang: 409
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .rsrc merge failure: duplicate leaf: type: 3 (ICON) name: 3 lang: 409
```
I don't even understand why it is using mingw32 at all?
I am on windows and I build the application for windows.
I have a working go compiler in the PATH.

Why is it going the most obscure way possible?
All I wanted is to add an Icon to my application 😅

**Comment by RuntimeRacer** [comment]
Ok first thing I figured: I needed to delete these files in the build dir:
![image](https://github.com/josephspurrier/goversioninfo/assets/49956579/cac8653d-bb74-406e-832d-89116733b168)
After this, it was able to build, but I couldn't run the application. Error code: "side-by-side configuration is incorrect"
Via Google I found out that it's manifest related. Apparently
```<assemblyIdentity
    type="win32"
    name="github.com.harmony-ai-solutions.harmony-link"
    version="0.1.8-beta2"
    processorArchitecture="*"/>```
doesn't like the string in the version. I changed it to:
```<assemblyIdentity
    type="win32"
    name="github.com.harmony-ai-solutions.harmony-link"
    version="0.1.8.0"
    processorArchitecture="*"/>```
And it worked.
