### ISSUE TITLE
Read version info

### ISSUE THREAD

**Issue by PaluMacil** [josephspurrier/goversioninfo#20]
I have been looking all morning for a way to read file info (version in particular) from a DLL or EXE, and I keep finding links to this package even though it does the opposite. Is there any interest in implementing a sort of resource file generator to pull this info into a file from where it is embedded? Either way, do you have any tips for where I should research this?

**Comment by josephspurrier** [comment]
I'm not sure of a Go library to do this. I'd probably take the easy route and call wmic from Go to get the information: http://windowstipoftheday.blogspot.com/2011/01/command-line-display-file-attribute.html

**Comment by PaluMacil** [comment]
Thanks. I'm using Powershell for a pretty similar approach to what you recommended, but I'd love to learn how to parse resources embedded into a binary.

**Comment by josephspurrier** [comment]
Have you looked at this? https://golang.org/pkg/debug/pe/. It may be a good place to start.
