### ISSUE TITLE
error on "go get"

### ISSUE THREAD

**Issue by Sebastien-Gutierrez** [josephspurrier/goversioninfo#24]
Hello, 
I have a strange behaviour on the "go get", I have an error message : 

src\github.com\josephspurrier\goversioninfo\goversioninfo.go:194:13: coff.Arch undefined (type *coff.Coff has no field or method Arch)

I'm under Windows 10 and I use the last version of akavel/rsrc

**Comment by josephspurrier** [comment]
Closing - there have been a bunch of changes since - please reopen if you're still having the issue.
