### ISSUE TITLE
how to set  the icon on the application status bar

### ISSUE THREAD

**Issue by rinetd** [josephspurrier/goversioninfo#25]
![20180610202948](https://user-images.githubusercontent.com/15907353/41201631-c50c65ac-6ced-11e8-83b0-98ccd988908e.png)
![20180610203615](https://user-images.githubusercontent.com/15907353/41201644-f232c788-6ced-11e8-8945-013ff4a24846.png)

**Comment by josephspurrier** [comment]
I found this article - https://github.com/therecipe/qt/wiki/Setting-the-Application-Icon#setting-the-icon-on-windows. Let me see if that is something I can integrate.

**Comment by josephspurrier** [comment]
Closing - reopen if you have any issues.
