### ISSUE TITLE
Version info is not embedded when passing main.go file to go build.

### ISSUE THREAD

**Issue by matsch01** [josephspurrier/goversioninfo#27]
Assume I have a  project structure like this:

- myapp
  - app
    + icon.ico
    + main.go
    + versioninfo.json
  - dist

When I run

```
./myapp/app>go generate
./myapp/app>go build main.go
```

The version info is not embedded inside the exe. Leaving off main.go from the go build command works. In this case it doesn't make a difference, but it does make a difference when you want to run go generate and build from another folder:

```
./myapp>go generate .\app
./myapp>go build -o .\dist\app.exe .\app\main.go
```

Do I have the command wrong? Should this be possible?

**Comment by josephspurrier** [comment]
Did you add this line to the top of your main.go file?

`//go:generate goversioninfo -icon=icon.ico`

**Comment by matsch01** [comment]
Yes of course.

**Comment by josephspurrier** [comment]
It seems like this is the same issue: https://github.com/golang/go/issues/16090. When you reference a .go file in build, it won't pick up the syso file.

**Comment by matsch01** [comment]
ok, thanks for finding the issue.

**Comment by KingRial** [comment]
For the record, I solved by following this https://github.com/golang/go/issues/16090#issuecomment-275223278 in the pointed ticket (Just do not use the file to build the in "go build" command)
