### ISSUE TITLE
Icon file not correctly closed

### ISSUE THREAD

**Issue by andydotxyz** [josephspurrier/goversioninfo#30]
In follow up to PR #28 and issue #29 here is the simplest test to illustrate the problem.

I am still working through an alternative solution but I can't figure out how the  `os.Open(fname)` in icon.go is being closed without the `defer f.Close()`

```go
package goversioninfo

import (
	"log"
	"os"
	"runtime"
	"testing"
)

func TestTempIcon(t *testing.T) {
	icoPath := "tmp.ico"
	outPath := "resource.syso"
	vi := &VersionInfo{}
	vi.IconPath = icoPath

	f, _ := os.Create(icoPath)
	err := f.Close()
	if err != nil {
		log.Println("Unexpected error closing new file")
	}

	vi.Build()
	vi.Walk()
	err = vi.WriteSyso(outPath, runtime.GOARCH)
	if err != nil {
		log.Println("Unexpected error writing resource")
	}

	err = os.Remove(icoPath)
	if err != nil {
		t.Fatal("Error deleting temporary icon", err)
	}
}
```

**Comment by andydotxyz** [comment]
With PR #28 applied this test passes, after the revert it fails - I think this captures the problem.

**Comment by andydotxyz** [comment]
OK I got to the bottom of it - the file was being used via the SectionReader that was added as a resource.
By buffering the data the problem is resolved.

This may not be the most elegant solution - some of the reflection was a little hard to understand.

**Comment by josephspurrier** [comment]
Great, thank you for figuring it out. I'm going to modify Travis-CI so it uses Windows to build and test - that should provide a way to run these tests.

**Comment by josephspurrier** [comment]
I was able to reproduce the issue in the CI/CD process: https://travis-ci.org/josephspurrier/goversioninfo/builds/491030373?utm_source=github_status&utm_medium=notification

**Comment by josephspurrier** [comment]
Once I merged in your changes, it fixed the issues: https://travis-ci.org/josephspurrier/goversioninfo/builds/491036422?utm_source=github_status&utm_medium=notification. Thanks for handling this. I'll merge it into master.
