### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by wegoodwin** [josephspurrier/goversioninfo#33]
Hi,

I just tried to use go build and I got the following error:

C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `C:\Users\WOG\AppData\Local\Temp\go-link-000595971\000000.o' is incompatible with i386:x86-64 output
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b001\exe\a.out.exe: .rsrc merge failure: corrupt .rsrc section
collect2.exe: error: ld returned 1 exit status

**Comment by the-goodies** [comment]
Same, using CGO (sqlite3) and golang 1.12.1 version. Tried with -ldflags="-linkmode=internal" flag as suggested somewhere, it compiles, but upon start throws some data dump gibberish related to sqlite3 and exits.
When downgraded to golang version 1.11.6 and compiled with that flag it finally successfully compiled and started. However when compressed the binary with [UPX](https://upx.github.io/) it didn't start again - throws data dump and exits.
So have to use an older version and no binary compression for me if i want to include that icon :cry:

**Comment by dhaavi** [comment]
Try the `-64` flag.
Effect: `generate 64-bit binaries`

**Comment by wegoodwin** [comment]
Hi Daniel,

Thanks for getting back to me.  It will be a few weeks before I can try this out.  I am in the middle of moving.

________________________________

**Comment by josephspurrier** [comment]
Closing - reopen if it's still an issue. Thanks @dhaavi!
