### ISSUE TITLE
How to request admin rights?

### ISSUE THREAD

**Issue by Lukentui** [josephspurrier/goversioninfo#38]
Hello! Thanks for ur project :3
I wanna require admin rights for run exe, but don'n know how :(

**Comment by Lukentui** [comment]
As far as I know its not documented.
I tried to add `<requestedExecutionLevel level="requireAdministrator" uiAccess="true" />` to `trustInfo/security` but it havent any result :/

**Comment by Lukentui** [comment]
not resolved for now(

**Comment by josephspurrier** [comment]
Have you tried right clicking on the exe and then clicking Run as Administrator?

**Comment by Lukentui** [comment]
> 
> 
> Have you tried right clicking on the exe and then clicking Run as Administrator?

Yesh it works :D
But it doesn't fit for me(

**Comment by Lukentui** [comment]
Solution:
.manifest like this:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<assemblyIdentity
    version="1.0.0.0"
    processorArchitecture="x86"
    name="filename.exe"
    type="win32"
/>
<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
        <requestedPrivileges>
            <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
        </requestedPrivileges>
    </security>
</trustInfo>
</assembly>`
