### ISSUE TITLE
Product version disappears when it ends with zero

### ISSUE THREAD

**Issue by speedyhoon** [josephspurrier/goversioninfo#4]
strings that appear: "0.0.10 ", "0.0.11"
strings that don't appear: "1.0", "0.10"

versioninfo.json contents:
{
	"StringFileInfo":
	{
		"ProductVersion": "1.0"
	}
}

test.go contents:
//go:generate goversioninfo

package main

func main(){
	print("hello")
}

**Comment by josephspurrier** [comment]
Verified. It's also interesting that when you put a character into SpecialBuild, ProductVersion shows up correctly.

**Comment by josephspurrier** [comment]
I changed the code so it's closer to spec. For some reason, it looks like windres was calculating lengths wrong and I was using that as an example. It should be more stable now.
