### ISSUE TITLE
"goversioninfo": executable file not found in $PATH

### ISSUE THREAD

**Issue by Tylous** [josephspurrier/goversioninfo#43]
When I try to run `go generate` I get the following message:
`running "goversioninfo": exec: "goversioninfo": executable file not found in $PATH` however go is in my PATH.

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin`

for reference, I am on OSX.

**Comment by paveljanda** [comment]
@Tylous The same happens to me. Could you please tell how did you resolve this issue? Thanks.

**Comment by josephspurrier** [comment]
@paveljanda can you do a `which` on goversioninfo and make sure it's in your $PATH?

**Comment by paveljanda** [comment]
`which` is not really working (not sure way, when passing the same $PATH content explicitly to which, it works..) but `type is`: `~/go/bin/goversioninfo`.

Also, `goversioninfo` is running fine.

**Comment by josephspurrier** [comment]
If `which` doesn't find it, it means the binary is not in your $PATH. Try this in your .bashrc or .bash_profile:

```bash
export GOBIN=/user/USERNAME/go/bin
export PATH=$PATH:$GOBIN
```

**Comment by paveljanda** [comment]
Problem solved, PATH can not contain `~` but full path.. :) Thanks!
