### ISSUE TITLE
Add 64 bit support

### ISSUE THREAD

**Issue by eukota** [josephspurrier/goversioninfo#5]
Would like to be able to link the syso's within 64 bit architecture.

**Comment by josephspurrier** [comment]
The version information should work with 64 bit. Is there something that is not working?

**Comment by eukota** [comment]
The resource.syso file does not work with 64 bit.
We have a pull request incoming where we added a -64 option. To build the binaries in 64 bit, need to call coff.Arch("amd64").

My coworker Chris will send a pull request.

**Comment by josephspurrier** [comment]
Fixed https://github.com/josephspurrier/goversioninfo/pull/6
