### ISSUE TITLE
Add Support for ARM builds

### ISSUE THREAD

**Issue by devinstasafe** [josephspurrier/goversioninfo#50]
For $Env:GOARCH="arm" I get the below error,

```log
# gitlab.com/instasafesdp/instasafe.ztna.services.go
C:\Users\RUNNER~1\AppData\Local\Temp\go-build1204466033\b001\_pkg_.a(resource.syso): 160839: unknown ARM relocation type 7
```

This is because the `resource.syso` does not have ARM support.

**Comment by yuk7** [comment]
Same issue.

So I created a pull request #51

**Comment by josephspurrier** [comment]
Great, thank you! I'll see if I can review this over the next couple days.

**Comment by josephspurrier** [comment]
Closed by https://github.com/josephspurrier/goversioninfo/releases/tag/v1.3.0
