### ISSUE TITLE
make versioninfo.json optional

### ISSUE THREAD

**Issue by ahmetb** [josephspurrier/goversioninfo#52]
I'm only interested in generating a .syso file with -icon parameter, but right now I have to have an empty versioninfo.json file with `{}` as the contents. This seems redundant as it's not at all used.

As an alternative, I'm doing this which is quite hacky.

```
//go:generate /bin/bash -c "go run github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest -icon=icon.ico <(echo '{}')"
```
or

```
//go:generate /bin/bash -c "go run github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest -icon=icon.ico - <<< '{}' "
```

but it works. 

It could be a lot better if I can just `//go:generate go run $TOOL -icon=...`. Thanks for creating this project!

**Comment by josephspurrier** [comment]
@ahmetb Give this a try: https://github.com/josephspurrier/goversioninfo/pull/55

Add `-skip-versioninfo`

**Comment by ahmetb** [comment]
Excellent, thanks. I am sure it works as expected. I'll update my usage as soon as it's merged.

**Comment by josephspurrier** [comment]
Released in: https://github.com/josephspurrier/goversioninfo/releases/tag/v1.4.0
