### ISSUE TITLE
dependencies not found (anymore)

### ISSUE THREAD

**Issue by damn-at** [josephspurrier/goversioninfo#54]
i already used your module in an tool.  
today i tried to rebuild it, and now it fails to build.  
tried to install goversioninfo

```bash
> go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo
no required module provides package github.com/josephspurrier/goversioninfo/cmd/goversioninfo; to add it:
        go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
```
```bash
> go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
github.com/josephspurrier/goversioninfo/cmd/goversioninfo imports
        github.com/josephspurrier/goversioninfo imports
        github.com/akavel/rsrc/binutil: cannot find module providing package github.com/akavel/rsrc/binutil
github.com/josephspurrier/goversioninfo/cmd/goversioninfo imports
        github.com/josephspurrier/goversioninfo imports
        github.com/akavel/rsrc/coff: cannot find module providing package github.com/akavel/rsrc/coff
github.com/josephspurrier/goversioninfo/cmd/goversioninfo imports
        github.com/josephspurrier/goversioninfo imports
        github.com/akavel/rsrc/ico: cannot find module providing package github.com/akavel/rsrc/ico
```
the same happens if i try to build my tool.   

UPDATE: 
it seems the download of the dependent module was corrupted or unpacked incorrect.
i unpacked it manually and now the install worked.

**Comment by josephspurrier** [comment]
Glad you found a workaround. This does work for me by adding `@latest` to the end:

```bash
$ go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
go: downloading github.com/josephspurrier/goversioninfo v1.3.0
go: downloading github.com/akavel/rsrc v0.10.2
```

I'm on: go version go1.16.2 darwin/amd64.

**Comment by jjliggett** [comment]
> Glad you found a workaround. This does work for me by adding `@latest` to the end:
> 
> ```shell
> $ go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
> go: downloading github.com/josephspurrier/goversioninfo v1.3.0
> go: downloading github.com/akavel/rsrc v0.10.2
> ```
> 
> I'm on: go version go1.16.2 darwin/amd64.

Adding `@latest` to the end of the go install command also fixed this issue for me which happened in a GitHub workflow using go 1.18.0 ( https://github.com/jjliggett/jjversion/pull/84 ). Thanks!
