### ISSUE TITLE
Is there any similar library in linux

### ISSUE THREAD

**Issue by hanxiaohuivc** [josephspurrier/goversioninfo#56]
Is there any similar library in linux
Hello. Is there a library similar to "goversioninfo" under linux to set the icons and information of executable files? I experimented with rsrc but it didn't work. thanks.

**Comment by josephspurrier** [comment]
It doesn't look like linux apps have embedded icons: https://stackoverflow.com/a/2126554.

Along the same lines is the version info is not standardized either: https://unix.stackexchange.com/a/58849

In Linux, everything is a file so it looks like the best way to set version info is to use the Go flag package: https://pkg.go.dev/flag.

Here is an example of how to set the version in Go: https://coderwall.com/p/l8xlka/golang-package-version-flag

**Comment by hanxiaohuivc** [comment]
> It doesn't look like linux apps have embedded icons: https://stackoverflow.com/a/2126554.
> 
> Along the same lines is the version info is not standardized either: https://unix.stackexchange.com/a/58849
> 
> In Linux, everything is a file so it looks like the best way to set version info is to use the Go flag package: https://pkg.go.dev/flag.
> 
> Here is an example of how to set the version in Go: https://coderwall.com/p/l8xlka/golang-package-version-flag

The link you shared worked for me, thanks a lot.
