### ISSUE TITLE
How to get file properties?

### ISSUE THREAD

**Issue by zhuqunzhou** [josephspurrier/goversioninfo#7]
How golang to get file detail properties,such as `File version`?

Thanks.

**Comment by josephspurrier** [comment]
I'm not exactly sure what you are asking, but this library only sets the file properties like File Version, it does not allow you to read them from other EXEs.

The File Version is actually set in versioninfo.json.

**Comment by josephspurrier** [comment]
I'm closing this. If you're still having a problem, please re-open.
