### ISSUE TITLE
Is it compatible with 64bits?

### ISSUE THREAD

**Issue by alepacheco** [josephspurrier/goversioninfo#8]
`go build` gives this error. 
What is wrong?
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

**Comment by josephspurrier** [comment]
It's builds fine in 32 or 64 bit Go 1.7 on Windows 10 x64 OS. Are you using http://www.mingw.org/? What's your operating system?

**Comment by alepacheco** [comment]
I was working in a 64 bits Windows 7 using cygwin, didn't notice those were refering to MinGw. Thanks
Any idea why this conflict? 

```
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-min
gw32/bin/ld.exe: i386 architecture of input file `C:\Users\PC\AppData\Local\Temp
\go-link-630187599\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status
```

**Comment by josephspurrier** [comment]
Now that I think about it, I don't believe you need cygwin or MinGw or build it. Try removing any cgo out of your build environment variables.

Can you send the output of: `go env`?

**Comment by conradfr** [comment]
I got the same problem as alepacheo.

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Developpe
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg
set CC=gcc
set GOGCCFLAGS=-m64 -mt
set CXX=g++
set CGO_ENABLED=1

**Comment by josephspurrier** [comment]
It looks like other people are having this issue as well (RSRC): https://github.com/mattn/go-sqlite3/issues/248. This issue then points to a workaround in this post: https://groups.google.com/forum/#!topic/golang-nuts/pZB_QQQk2Z4.

Can you try with this command: go build -ldflags "-linkmode=internal"

**Comment by josephspurrier** [comment]
Please reopen if you are still having issues.
