### ISSUE TITLE
Allow to specify the icon file as part of versioninfo.json

### ISSUE THREAD

**Issue by sschuberth** [josephspurrier/goversioninfo#9]
Usually, the main icon is specified as part of a Windows `.rc` file. With `versioninfo.json` being more or less the replacement for the `.rc` file, it would make sense to also be able to specify the icon file name in there. Also, this helps to keep the information in one place, and not spread it across `versioninfo.json` and command line options.

**Comment by josephspurrier** [comment]
It would be a good idea. I haven't had much time to work on this. If you want to submit a PR, I'd check it over!

**Comment by sschuberth** [comment]
Sorry, as I'm not currently using Go anymore, I'll not have time to work on a PR.
